[package]
name = "mila"
version = "0.1.0"
authors = ["thane98"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.20"
byteorder = "1.3.4"
encoding_rs = "0.8.20"
nintendo-lz = "0.1.3"
linked-hash-map = { version = "0.5.3", features = ["serde_impl"] }
maplit = "1.0.2"
